### ISSUE TITLE
Is it possible to change the Audio Codec used?

### ISSUE THREAD

**Issue by sarinrohan** [pchab/AndroidRTC#10]
While running the app on my phone, when I check the logs on Eclipse, I find that it sets the audio codec as Opus at 32kbits. Since the internet connection I am using is pretty poor, is it possible to adjust the SendCodec bitrate to a lower value in your app for better audio?

Also, would it help to use the compiled library for Google's WebRTCDemo and create a VoiceEngine and simply edit the sendcodec?

Thanks.

**Comment by pchab** [comment]
Hi, I've updated the libjingle and you should now be able to change audio and video codecs (as well as some other parameters).
