### ISSUE TITLE
Not able to control VideoSource 

### ISSUE THREAD

**Issue by Rajesh1306** [pchab/AndroidRTC#125]
I want to stop local video streaming on button press and enable it again on another button press. For stopping I attempted to call my method in RTCActivity as below

if(client != null){ client.stopVideoSource(); }

which in turn call below method in WebRtcClient. However doing so is not helping me to stop the local video streaming to client.

public void stopVideoSource() { if(videoSource != null){ videoSource.stop(); }

Similarly for restart I used videoSource.restart() for restarting the local stream to peer but is not working.

Can some one help me to resolve this issue?

@pchab. @chabardt. can you assist please?

**Comment by karan23** [comment]
Hi Rajesh,

Have you got any solution to this problem??

**Comment by Rajesh1306** [comment]
@karan, get your video track from stream and disable it. It will pause your video streaming
