### ISSUE TITLE
Getting black activity in android client

### ISSUE THREAD

**Issue by karan23** [pchab/AndroidRTC#126]
I have tried this code in android device and deployed projectRtc on my machine and change the host (to 10.0.0.48 (local ip)) in strings.xml but still its showing the black activity. Is there a way to get it work.

**Comment by aliumujib** [comment]
I have the same issue, have you found a way around this? I am completely lost and inexperienced at this.

**Comment by karan23** [comment]
Hi,

Sorry for late update, the mistake was mine as I was in a different network in mobile and the server was deployed in different network.

**Comment by Tfancy** [comment]
Excuse me ,
I have a question that there would be two client,but the project has just one AndroidRTC. Could you told me what the other lient is ?

**Comment by pchab** [comment]
The other client is a small JavaScript app in the projectRtc repo. Just start the express server (npm start) and it will be available at localhost:3000
