### ISSUE TITLE
Can't connect when behind proxy server

### ISSUE THREAD

**Issue by sojharo** [pchab/AndroidRTC#15]
I was doing demo with your code couple of days ago. I realized I was not able to connect when I was behind the proxy. On further inspection, I found that issue is with the android-websocket library that you are using. The author of this library has declared this library deprecated. Also, in his new libraries he is not looking into this issue.

Have you yourself found any work around for this problem? Kindly, let me know if you have any work around.

Thanks

**Comment by pchab** [comment]
Switched to socket.io-client library.
