### ISSUE TITLE
Remote Streams black

### ISSUE THREAD

**Issue by KainanSu** [pchab/AndroidRTC#196]
When use with [ProjectRTC](github.com/pchab/ProjectRTC) , 

The vedio can play in local window successfully, but the remote window is always black. It looks like that it is attempt to connect.

Something like this.
![something like this](https://user-images.githubusercontent.com/42830139/112277882-2f960300-8cbd-11eb-85c5-ac00580fd158.jpg)

Could you guys help help me? please.

**Comment by LuossD** [comment]
me too

**Comment by KainanSu** [comment]
这个问题我多次测试，解决不了。后来换了一个实现的demo，可以参考一下这篇博客https://blog.csdn.net/u011077027/article/details/86225524 ，可以使用。

**Comment by utills** [comment]
Me too same

**Comment by wying111** [comment]
+1

**Comment by KainanSu** [comment]
> 这个问题我多次测试，解决不了。后来换了一个实现的demo，可以参考一下这篇博客https://blog.csdn.net/u011077027/article/details/86225524 ，可以使用。

refer to the solution above.
