### ISSUE TITLE
App showing no stream black screen on start of application.

### ISSUE THREAD

**Issue by umerk44** [pchab/AndroidRTC#23]
I have followed the insturction now when i try to run the android app it just show the black screen. Actually i wanted to do a peer to peer live streaming using this, is it possible?

**Comment by pchab** [comment]
Yes it is possible. You must be running the ProjectRTC server and use its IP address in the android app (in strings.xml).

**Comment by umerk44** [comment]
I set the IP in string.xml file but sill i am not able to see the stream, when i hit "http://localhost:3000" in my browser it says "unable to connect". By peer to peer i mean between two android devices not between computer and android device. How can i achieve that?

**Comment by pchab** [comment]
If you can't see your web socket server at localhost:3000 means it's not configured right. It is needed even for android to android communication.

**Comment by umerk44** [comment]
This is how it looks when i run the server http://postimg.org/image/6avhoos5v/

**Comment by rootmonty** [comment]
Hi ,Even after changing the host name in the RtcActivity I am getting a black screen.I am running the server and its running fluently without an error and its showing the screening on the localhost:3000 as well for browser but unfortunately I am unable to connect my clients on the server.I have installed the app on two clients and am testing and both of them are giving a black-grey bright screen with nothing on it.
