### ISSUE TITLE
Release Camera when exit app

### ISSUE THREAD

**Issue by VAdaihiep** [pchab/AndroidRTC#24]
When exit app (by press Back button): 
The partner still hear my voice. 
Wait for about 5 seconds, app crash because of OutOfMemory error. 

I think this crash because when exit app, it's not release camera and not close connection.

So please help me to fix this issue.
Thanks in advance!

**Comment by umerk44** [comment]
do you found any solution?

**Comment by VAdaihiep** [comment]
Not yet. I try to use newer Android WebRTC lib, app quit fine but it crash when re-open :( You can looking at https://code.google.com/p/webrtc: trunk/webrtc/examples/android.  If you found the solution, please share with me.

**Comment by vdung7** [comment]
I have the same problem with you, and my solution idea is like @VAdaihiep too. I think we must do a lot of changes to make camera and connection could close safer (after press Back button).

**Comment by pchab** [comment]
See [issue#32](https://github.com/pchab/AndroidRTC/issues/32)
