### ISSUE TITLE
webrtc: Too long processing time of Incoming frame: 20ms

### ISSUE THREAD

**Issue by umerk44** [pchab/AndroidRTC#26]
I am getting this warning message "webrtc: Too long processing time of Incoming frame: 20ms" and time gets increasing more and more and finally i got the OutOfMemory issue because it grows heap up to the limit even though i have added "android:largeHeap = true" in manifest.

**Comment by vdung7** [comment]
I have the same problem. I think the problem due to Camera isn't released after connection is closed. And I'm trying to found a safe way to close connect from device (after exit app by press Back button).
If you found the solution, please share with me. :sob:

**Comment by pchab** [comment]
See [issue#32](https://github.com/pchab/AndroidRTC/issues/32)
