### ISSUE TITLE
How can i improve the sound quality 

### ISSUE THREAD

**Issue by umerk44** [pchab/AndroidRTC#33]
I am facing sound quality issues. The video quality of stream is fine but audio is not so great there is echo and noise in the sound. How can i improve the sound quality?

**Comment by pchab** [comment]
updated libjingle in my app. Quality should be better. If not, you should now be able to modify some parameters (codec, bitrate) to improve it.

**Comment by sriharisri** [comment]
I am facing same problem.Please tell me the solution.How to improve audio quality.
