### ISSUE TITLE
Having trouble opening your project using Android Studio

### ISSUE THREAD

**Issue by bwilks128** [pchab/AndroidRTC#35]
Hi,

I'm very interested in trying your Android client and I see from the latest check-in that you are using Android Studio. I'm pretty new to all this and when I try to open the source in Android Studio as an existing project, it says it can't find some gradle settings.

Any hints on how I would open your project in Android Studio would be greatly appreciated.

Thanks!
Barry

**Comment by pchab** [comment]
Hi Barry,

Thanks for reporting. Apparently I should not have included the whole .idea folder in the .gitignore.
You should be able to open the project now.

**Comment by bwilks128** [comment]
Thanks Pierre! It's working now.
