### ISSUE TITLE
EGLContext issue 

### ISSUE THREAD

**Issue by nourhanadel59** [pchab/AndroidRTC#37]
i faced this issue when trying to run the new update of this project :
at org.webrtc.VideoRendererGui.onSurfaceCreated(VideoRendererGui.java:791)
FATAL EXCEPTION: GLThread 16547
The method getEGLContext() is undefined for the type EGLContext
at com.firefly.rtc.RtcActivity.init(RtcActivity.java:97)

client = new WebRtcClient(this, mSocketAddress, params, VideoRendererGui.getEGLContext());
public WebRtcClient(RTCListener listener, String host, PeerConnectionParameters params,EGLContext mEGLcontext);

**Comment by pchab** [comment]
Are you trying to run the project as it is ?

**Comment by nourhanadel59** [comment]
now i fix this problem .. 
but now when trying to run with my server only appear black screen .. how can i resolve this issue ?

**Comment by pchab** [comment]
see [issue#34](https://github.com/pchab/AndroidRTC/issues/34)
If nothing happens when you launch the app (black screen), it means that your client could not connect to the server.

**Comment by nourhanadel59** [comment]
this is my logcat:
new io instance for "my server url"
Returning key pair
Making certificate for WebRTC
Returning certificate
GC_CONCURRENT freed 1680K, 37% free 9624K/15043K, paused 14ms+10ms, total 147ms

**Comment by pchab** [comment]
Are you using ProjectRTC server or a custom server ?

**Comment by nourhanadel59** [comment]
custom server

**Comment by pchab** [comment]
The client is initialised when he receives a message {'id': <id string from server>}
You should look at ProjectRTC to see what message you must implement. Or modify the message handler if you want to change the server side.

**Comment by nourhanadel59** [comment]
ammm .. but my server now connected .. right ?

**Comment by pchab** [comment]
I guess. It must handle the signaling part of webrtc.

**Comment by nourhanadel59** [comment]
i am download server of this app that called ProjectRTC .. I found the apk of this project but also when try to running it .. just gave me a black screen only !

**Comment by pchab** [comment]
Where did you find that apk ? Previous commit of ProjectRTC had the apk of an old version of androidRTC but I removed it. If you wish, I can put the latest version of androidrtc on the repo, or you can build it with android studio.

**Comment by nourhanadel59** [comment]
yes .. can you share it with me please ?

**Comment by pchab** [comment]
Ok, but again, this apk will point to my own server. If you want to use yours, you need to clone the git, open it with android studio, edit the host value in strings.xml and build.

**Comment by nourhanadel59** [comment]
yes i see .. i am already work on it .. but i want to see working apk ..
i want to ask .. after success connection with server .. what the expected response i should receive ? .. and from and payload refer to what ?
 JSONObject json = argument.getJSONObject(0);
			              String from = json.getString("from");
			              String type = json.getString("type");
			              JSONObject payload = null;
			              if(!type.equals("init")) {
			                payload = json.getJSONObject("payload");
			              }
thanks in advance for your help .

**Comment by nourhanadel59** [comment]
yes i see .. i am already work on it .. but i want to see working apk ..
i want to ask .. after success connection with server .. what the expected
response i should receive ? .. and from and payload refer to what ?
JSONObject json = argument.getJSONObject(0);
String from = json.getString("from");
String type = json.getString("type");
JSONObject payload = null;
if(!type.equals("init")) {
payload = json.getJSONObject("payload");
}
thanks in advance for your help .

**Comment by pchab** [comment]
[Link](https://github.com/pchab/ProjectRTC/raw/master/app-debug.apk) to the android apk.
After a successful connection, the server sends a "id" type message, the payload contains the id of the connected client.
After that when another client calls, there will be a standard webrtc exchange of message: offer/answer and ICE candidates. The payload will contain the sdp or the candidates.

**Comment by Nickx27** [comment]
Hi, 
I just tried the project RTC along with the AndroidRTC and it works perfect. I was wondering if we have an option to switch only to audio call(while connected in video call). If there is already a functionality in the existing code, please do let me know.

Thanks

**Comment by johnsonzhu** [comment]
I use this demo in one LAN, it works. but it does not work in different LAN with my own turn server(rfc5766-turn-server). why? turn server had allot new relay server for each client. but the client cannot send package to the relay server. Would u mind to tell me how can I use the demo in different LAN?
Thank u so much.
