### ISSUE TITLE
No Audio/Video on Android client

### ISSUE THREAD

**Issue by Ponsen** [pchab/AndroidRTC#4]
Hi!

First of all: Nice project! But I have a little problem getting it running properly. The Problem is, that I cannot receive any video or audio data on the Android client, while Browser to Browser is working fine. But the strange thing is, that the Client is sending A/V data just fine.

Any suggestions?

PS: I've tried running nodejs version 0.8 and 0.10 with no difference. The problem persists on different Android devices with version 4.0.3, 4.0.4, 4.2.2 and 4.4.2.

Thank you very much in advance!!

**Comment by CNSHCP** [comment]
Hi I am trying to use AndroidRTC in my application for video/audio calls but facing some issues. I have  attached the screenshot of console log cat containing errors.
![screenshot from 2015-09-22 15 55 21](https://cloud.githubusercontent.com/assets/14756935/10016123/61d65344-6142-11e5-85ae-3d71b71d5b6a.png)
