### ISSUE TITLE
App not working when using difference Network

### ISSUE THREAD

**Issue by iraj-wisilica** [pchab/AndroidRTC#46]
Dear Sir,

I have configured ProjectRTC and it is successfully running in my PC browser. When I run AndroidRTC it works fine. Because both Android mobile and PC are in the same network. But when changed the PC to another network, I get a black screen in my Android app. Please help me to resolve this issue. I have gone and found that we have to use TURN or STUN server using ICE framework. Please help me to connect TURN server from my Android RTC.

**Comment by pchab** [comment]
can you copy/paste your [strings.xml](https://github.com/pchab/AndroidRTC/blob/android-studio/app/src/main/res/values/strings.xml) here ?

**Comment by VAdaihiep** [comment]
@iraj-wisilica I think the reason is your PC have not static IP address.

**Comment by iraj-wisilica** [comment]
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="app_name">AndroidRTC</string>
    <string name="host">192.168.1.22</string>
    <string name="port">3000</string>
    <string name="action_settings">Options</string>
</resources>

**Comment by pchab** [comment]
As VAdaihiep said, this is a local IP address. This will obviously not work on a different network.

**Comment by iraj-wisilica** [comment]
Then can you please explain the purpose STUN server in browser and Android app? Is there any other way to resolve this issue?

**Comment by iraj-wisilica** [comment]
Then can you please explain the purpose STUN server in browser and Android app? Is there any other way to resolve this issue?

**Comment by Bala206** [comment]
1)  When you start AndroidRTC app on device-1 then it will show a popup. Call someone
     Share the link from device-1 to device-2 (via email, whatsapp sms etc)
      in device-2 you will get that link
      click that link
      Android will let you choose from different apps (like chrome, browser and AndroidRTC)
      choose AndroidRTC. Now Device-1 App Crashed ?

2)  And Also Browser shows device-list.In list View button shows device video streaming correctly.
     When click on Call button device side App crash?

Can any one know answer help me how to fix it?
