### ISSUE TITLE
Can I use a switch in AndroidRTC for switching audio/video call while two users are connected

### ISSUE THREAD

**Issue by Nickx27** [pchab/AndroidRTC#52]
Hi, Can I able to switch between audio/video while webrtc client connections are established.

**Comment by pchab** [comment]
Hi, This is not implemented as of now.
You could probably take a look at this [pull request](https://github.com/pchab/AndroidRTC/pull/20) if you want to do it yourself.

**Comment by Nickx27** [comment]
One more question, can I implement sending a message(chat) while connected to webrtc client. If do, how can it be implemented in AndroidRTC.

**Comment by pchab** [comment]
androidRtc uses socket.io to send the SDP messages. http://socket.io/ already provide examples for building a simple chat app.
