### ISSUE TITLE
How to get the streams list on AndroidRTC

### ISSUE THREAD

**Issue by gujiaxi** [pchab/AndroidRTC#59]
Is there any way to get the remote streams list (Name - ID) on the Android side?

**Comment by hoang89yenthe** [comment]
You can get that in file streams.json on the server

**Comment by hoang89yenthe** [comment]
The remote streams list are stored in http:localhost:3000/streams.json .

**Comment by kumar5572** [comment]
Ya i can get it on the server how can i get on the Android side
