### ISSUE TITLE
How to add Audio only call's

### ISSUE THREAD

**Issue by VijaiAaditya** [pchab/AndroidRTC#8]
Is it possible to make audio only call's. Can you please help me how to add voice only call support.

I tried by adding   

 AudioManager audioManager =
        ((AudioManager) getSystemService(AUDIO_SERVICE));
    // TODO(fischman): figure out how to do this Right(tm) and remove the
    // suppression.
    @SuppressWarnings("deprecation")
    boolean isWiredHeadsetOn = audioManager.isWiredHeadsetOn();
    audioManager.setMode(isWiredHeadsetOn ?
        AudioManager.MODE_IN_CALL : AudioManager.MODE_IN_COMMUNICATION);
    audioManager.setSpeakerphoneOn(!isWiredHeadsetOn);

lMS.addTrack(factory.createAudioTrack("ARDAMSa0"));
      pc.addStream(lMS, new MediaConstraints());

pcConstraints.mandatory.add(new MediaConstraints.KeyValuePair("OfferToReceiveAudio", "true"));
    pcConstraints.mandatory.add(new MediaConstraints.KeyValuePair("OfferToReceiveVideo", "false"));

But nothing helped me to make  a audio only call.

**Comment by kakopappa** [comment]
I am also trying to make only audio calls work.

**Comment by borhanreo** [comment]
How can i get all user list? please help me
