### ISSUE TITLE
No video rendered when resuming

### ISSUE THREAD

**Issue by OrNot** [pchab/AndroidRTC#9]
1. Open the app and don't have to send the invitation to a peer. just ignore that intent
2. the local video shown. 
3. hide the app 
4.  go back (or resume from the recent launch list ) the app
5. nothing will be rendered .

It seems something goes wrong with the opengl configuration. 

Maybe worth taking a look. 

TIA.

**Comment by pchab** [comment]
See [issue#32](https://github.com/pchab/AndroidRTC/issues/32)
