### ISSUE TITLE
How to keep video on while screen is closed

### ISSUE THREAD

**Issue by TuringTW** [pchab/AndroidRTC#97]
Hi!
When I turned off the screen, the voice kept streaming but the video stop.
Is there anyone meet the same problem?
Should I put webRTC client into service?

**Comment by CaoQuocTuan** [comment]
i think, you need delete videoSource.Stop() at onPause()

**Comment by TuringTW** [comment]
Ha! Thanks!!!
I forget to remove that  XD
But it seems that videosource.stop() in the original androidRTC didn't work properly. 
While onpause in webrtcclient is called when the screen is off, video source didn't stop.
